[project]
name = "networkx-clustering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "networkx>=3.4.1",
    "pandas>=2.2.3",
    "scipy>=1.14.1",
]
