[project]
name = "networkx-clustering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.4.1",
    "polars-lts-cpu>=1.21.0",
    "scipy>=1.14.1",
]
